'''
dmstudio.notebook_builder
--------------------------

Provides the NotebookBuilder class for programmatically generating Jupyter
Notebook (.ipynb) files from Datamine Studio RM workflow steps.

The intent is that AI agents write workflows to a notebook for full
auditability rather than executing commands directly from the terminal.
The notebook can then be executed with:

    jupyter nbconvert --to notebook --execute --inplace <notebook>.ipynb

Usage:
------
    from dmstudio.notebook_builder import NotebookBuilder

    nb = NotebookBuilder('my_workflow.ipynb', title='Drillhole Workflow')
    nb.add_markdown('## Step 1: Initialize')
    nb.add_code("from dmstudio import dmcommands\\ncmd = dmcommands.init(version='StudioRM')")
    nb.add_markdown('## Step 2: Sort collars')
    nb.add_code("cmd.mgsort(in_i='collars', out_o='sorted_collars', keys_f=['BHID'])")
    nb.save()
'''

import json
import os
import datetime


class NotebookBuilder:
    '''
    NotebookBuilder
    ---------------

    Programmatically builds a Jupyter Notebook (.ipynb) file by accumulating
    markdown and code cells, then writing the result as a valid nbformat v4 JSON.

    Parameters:
    -----------
    filename: str
        Output path for the .ipynb file (e.g. 'workflow.ipynb').
    title: str
        Optional title for an auto-generated header markdown cell.
        If provided, a markdown cell with an H1 heading and a timestamp is
        prepended as the first cell.

    Methods:
    --------
    add_markdown(text)
        Append a markdown cell containing ``text``.
    add_code(code)
        Append a code cell containing ``code``.
    save()
        Write the notebook to disk as a valid nbformat v4 JSON file.
    '''

    _NBFORMAT = 4
    _NBFORMAT_MINOR = 5

    def __init__(self, filename, title=None):
        self.filename = filename
        self._cells = []

        if title:
            ts = datetime.datetime.now().strftime('%Y-%m-%d %H:%M')
            self.add_markdown(
                '# {}\n\n'
                '_Generated by dmstudio.notebook_builder on {}_\n\n'
                '> Run with: `jupyter nbconvert --to notebook --execute --inplace {}`'.format(
                    title, ts, os.path.basename(filename)
                )
            )
            # Preamble setup cell
            self.add_code(
                '# Auto-generated preamble\n'
                'import warnings\n'
                'warnings.filterwarnings("ignore")\n'
                'print("Notebook: {}")'.format(title)
            )

    def add_markdown(self, text):
        '''
        add_markdown
        ------------

        Append a markdown cell.

        Parameters:
        -----------
        text: str
            Markdown text. Multi-line strings are split into source lines.
        '''
        lines = _split_lines(text)
        self._cells.append({
            'cell_type': 'markdown',
            'metadata': {},
            'source': lines,
        })
        return self

    def add_code(self, code, outputs=None):
        '''
        add_code
        --------

        Append a code cell.

        Parameters:
        -----------
        code: str
            Python source code for the cell.
        outputs: list or None
            Optional pre-populated cell outputs (nbformat output dicts).
            Defaults to an empty list.
        '''
        lines = _split_lines(code)
        self._cells.append({
            'cell_type': 'code',
            'execution_count': None,
            'metadata': {},
            'outputs': outputs or [],
            'source': lines,
        })
        return self

    def save(self):
        '''
        save
        ----

        Write the notebook to disk as a valid Jupyter Notebook (nbformat v4).

        Returns:
        --------
        str
            Absolute path to the written notebook file.
        '''
        notebook = {
            'nbformat': self._NBFORMAT,
            'nbformat_minor': self._NBFORMAT_MINOR,
            'metadata': {
                'kernelspec': {
                    'display_name': 'dmstudio',
                    'language': 'python',
                    'name': 'dmstudio',
                },
                'language_info': {
                    'name': 'python',
                    'version': '3.9.0',
                },
            },
            'cells': self._cells,
        }

        abs_path = os.path.abspath(self.filename)
        with open(abs_path, 'w', encoding='utf-8') as fh:
            json.dump(notebook, fh, indent=1, ensure_ascii=False)

        return abs_path

    def __repr__(self):
        return 'NotebookBuilder(filename={!r}, cells={})'.format(
            self.filename, len(self._cells)
        )


# ---------------------------------------------------------------------------
# Helper
# ---------------------------------------------------------------------------

def _split_lines(text):
    '''Split multi-line text into a list of strings with trailing newlines, as
    required by nbformat cell source format. The last line does NOT have a
    trailing newline.'''
    lines = text.split('\n')
    result = []
    for i, line in enumerate(lines):
        if i < len(lines) - 1:
            result.append(line + '\n')
        else:
            if line:  # skip empty trailing line
                result.append(line)
    return result
