import json

notebook_path = 'run_tests.ipynb'

with open(notebook_path, 'r', encoding='utf-8') as f:
    nb = json.load(f)

# Reconstruct all the helper code lines
helper_code_lines = [
    "import os\n",
    "import sys\n",
    "import shutil\n",
    "import glob\n",
    "import time\n",
    "import datetime\n",
    "import traceback\n",
    "import argparse\n",
    "import nbformat\n",
    "from nbconvert.preprocessors import ExecutePreprocessor, CellExecutionError\n",
    "from dmstudio import agent, initialize\n",
    "from dmstudio.command_registry import VERIFIED_COMMANDS\n",
    "\n",
    "def reset_com_state(oScript):\n",
    "    try:\n",
    "        if oScript is not None:\n",
    "            try:\n",
    "                oScript.Parsecommand(\"can\")\n",
    "            except Exception:\n",
    "                pass\n",
    "            hwnd = getattr(oScript, 'WindowHandle', None)\n",
    "            if hwnd:\n",
    "                import win32con, win32api\n",
    "                win32api.PostMessage(hwnd, win32con.WM_KEYDOWN, win32con.VK_ESCAPE, 0)\n",
    "                win32api.PostMessage(hwnd, win32con.WM_KEYUP, win32con.VK_ESCAPE, 0)\n",
    "    except Exception as e:\n",
    "        print(f\"  [Warning] Failed to reset COM state: {e}\")\n",
    "\n",
    "def clear_sandbox(sandbox_dir):\n",
    "    print(f\"Clearing sandbox: {sandbox_dir}\")\n",
    "    for item in os.listdir(sandbox_dir):\n",
    "        item_lower = item.lower()\n",
    "        if item_lower == 'project.rmproj' or item_lower.startswith('project.rmproj.'):\n",
    "            continue\n",
    "        item_path = os.path.join(sandbox_dir, item)\n",
    "        try:\n",
    "            if os.path.isdir(item_path):\n",
    "                shutil.rmtree(item_path)\n",
    "            else:\n",
    "                os.remove(item_path)\n",
    "        except Exception as e:\n",
    "            print(f\"  [Warning] Failed to remove {item} from sandbox: {e}\")\n",
    "\n",
    "def patch_notebook_paths(nb_path, repo_root_abs):\n",
    "    with open(nb_path, 'r', encoding='utf-8') as f:\n",
    "        nb = nbformat.read(f, as_version=4)\n",
    "    modified = False\n",
    "    for cell in nb.cells:\n",
    "        if cell.cell_type == 'code':\n",
    "            lines = cell.source.splitlines()\n",
    "            new_lines = []\n",
    "            for line in lines:\n",
    "                if 'repo_root = os.path.abspath(os.path.join(' in line:\n",
    "                    indent = line[:line.find('repo_root')]\n",
    "                    new_lines.append(f'{indent}repo_root = r\"{repo_root_abs}\"')\n",
    "                    modified = True\n",
    "                else:\n",
    "                    new_lines.append(line)\n",
    "            cell.source = '\\n'.join(new_lines)\n",
    "    if modified:\n",
    "        with open(nb_path, 'w', encoding='utf-8') as f:\n",
    "            nbformat.write(nb, f)\n",
    "        print(\"  Patched repo_root path to absolute.\")\n",
    "\n",
    "def run_test_suite(args):\n",
    "    parser = argparse.ArgumentParser()\n",
    "    parser.add_argument('--all', action='store_true')\n",
    "    parser.add_argument('--workflows', action='store_true')\n",
    "    parser.add_argument('--processes', action='store_true')\n",
    "    parser.add_argument('--files', action='store_true')\n",
    "    parser.add_argument('--only', type=str)\n",
    "    parser.add_argument('--start', type=str)\n",
    "    parser.add_argument('--end', type=str)\n",
    "    parser.add_argument('--timeout', type=int, default=60)\n",
    "    \n",
    "    args = [a for a in args if a]\n",
    "    parsed_args = parser.parse_args(args)\n",
    "\n",
    "    repo_root = os.path.abspath(os.getcwd())\n",
    "    sandbox_dir = os.path.join(repo_root, 'tutorials', 'test_sandbox')\n",
    "    expected_project_path = os.path.join(sandbox_dir, 'Project.rmproj')\n",
    "\n",
    "    existing_pp = os.environ.get('PYTHONPATH', '')\n",
    "    if repo_root not in existing_pp:\n",
    "        os.environ['PYTHONPATH'] = os.path.pathsep.join([repo_root, existing_pp]) if existing_pp else repo_root\n",
    "\n",
    "    print(\"Connecting to running Datamine Studio RM instance...\")\n",
    "    try:\n",
    "        oScript = initialize.studio('StudioRM')\n",
    "        print(f\"Connected to: {oScript.Caption}\")\n",
    "    except Exception as e:\n",
    "        print(f\"\\n[ERROR] Could not connect to Datamine Studio RM: {e}\")\n",
    "        return\n",
    "\n",
    "    project = oScript.ActiveProject\n",
    "    if project is None:\n",
    "        print(\"\\n[ERROR] No active project in Studio RM!\")\n",
    "        return\n",
    "\n",
    "    active_folder = os.path.normpath(project.Folder).lower()\n",
    "    expected_folder = os.path.normpath(sandbox_dir).lower()\n",
    "    if active_folder != expected_folder:\n",
    "        print(f\"\\n[ERROR] Active project folder mismatch! Active: {active_folder}, Expected: {expected_folder}\")\n",
    "        return\n",
    "\n",
    "    notebook_queue = []\n",
    "    \n",
    "    # 1. Workflows\n",
    "    if parsed_args.all or parsed_args.workflows or (not parsed_args.processes and not parsed_args.files and not parsed_args.only):\n",
    "        workflows_dir = os.path.join(repo_root, 'tutorials', 'workflows')\n",
    "        for folder in os.listdir(workflows_dir):\n",
    "            folder_path = os.path.join(workflows_dir, folder)\n",
    "            if os.path.isdir(folder_path):\n",
    "                for f in os.listdir(folder_path):\n",
    "                    if f.endswith('.ipynb'):\n",
    "                        notebook_queue.append({\n",
    "                            'name': f.replace('.ipynb', ''),\n",
    "                            'type': 'workflow',\n",
    "                            'dir': folder_path,\n",
    "                            'file': f\n",
    "                        })\n",
    "\n",
    "    # 2. Collections (Processes and Files)\n",
    "    if parsed_args.all or parsed_args.processes or parsed_args.files or (parsed_args.only and not parsed_args.workflows):\n",
    "        try:\n",
    "            from dmstudio import dmfiles\n",
    "            cls_file = dmfiles.init\n",
    "            dmfiles_methods = {name.lower() for name in dir(cls_file) if not name.startswith('_') and callable(getattr(cls_file, name))}\n",
    "        except Exception:\n",
    "            dmfiles_methods = {'inpfil'}\n",
    "            \n",
    "        collections_dir = os.path.join(repo_root, 'tutorials', 'collections')\n",
    "        if os.path.exists(collections_dir):\n",
    "            for item in os.listdir(collections_dir):\n",
    "                item_path = os.path.join(collections_dir, item)\n",
    "                if os.path.isfile(item_path) and item.endswith('_example.ipynb'):\n",
    "                    cmd_name = item.replace('_example.ipynb', '').lower()\n",
    "                    if cmd_name in VERIFIED_COMMANDS:\n",
    "                        is_dmfile = cmd_name in dmfiles_methods\n",
    "                        if parsed_args.processes and not parsed_args.all and not parsed_args.files and is_dmfile:\n",
    "                            continue\n",
    "                        if parsed_args.files and not parsed_args.all and not parsed_args.processes and not is_dmfile:\n",
    "                            continue\n",
    "                        notebook_queue.append({\n",
    "                            'name': cmd_name,\n",
    "                            'type': 'file' if is_dmfile else 'process',\n",
    "                            'dir': collections_dir,\n",
    "                            'file': item\n",
    "                        })\n",
    "\n",
    "    if parsed_args.only:\n",
    "        names_to_keep = [n.strip().lower() for n in parsed_args.only.split(',')]\n",
    "        notebook_queue = [nb for nb in notebook_queue if nb['name'].lower() in names_to_keep]\n",
    "\n",
    "    if not notebook_queue:\n",
    "        print(\"No notebooks found matching the criteria.\")\n",
    "        return\n",
    "\n",
    "    print(f\"\\nQueued {len(notebook_queue)} notebooks for validation.\")\n",
    "    print(\"=\" * 60)\n",
    "\n",
    "    test_results_root = os.path.join(repo_root, 'tutorials', 'test_results')\n",
    "    run_id = datetime.datetime.now().strftime(\"run_%Y%m%d_%H%M%S\")\n",
    "    results_dir = os.path.join(test_results_root, run_id)\n",
    "    os.makedirs(results_dir, exist_ok=True)\n",
    "\n",
    "    results = []\n",
    "\n",
    "    for idx, nb_info in enumerate(notebook_queue, start=1):\n",
    "        name = nb_info['name']\n",
    "        nb_type = nb_info['type']\n",
    "        src_dir = nb_info['dir']\n",
    "        nb_file = nb_info['file']\n",
    "        \n",
    "        print(f\"\\n[{idx}/{len(notebook_queue)}] Running {nb_type.upper()}: {name}...\")\n",
    "        try:\n",
    "            with agent.dialog_dismiss_context(title='Studio RM'):\n",
    "                if oScript.ActiveProject is not None:\n",
    "                    oScript.ActiveProject.CloseNoSave()\n",
    "                    time.sleep(1.0)\n",
    "                oScript.OpenProject(expected_project_path)\n",
    "                time.sleep(1.5)\n",
    "        except Exception as e:\n",
    "            print(f'  [Warning] Failed to re-open project: {e}')\n",
    "            \n",
    "        clear_sandbox(sandbox_dir)\n",
    "        shutil.copy2(os.path.join(src_dir, nb_file), os.path.join(sandbox_dir, nb_file))\n",
    "        sandbox_nb_path = os.path.join(sandbox_dir, nb_file)\n",
    "        \n",
    "        try:\n",
    "            patch_notebook_paths(sandbox_nb_path, repo_root)\n",
    "        except Exception as e:\n",
    "            print(f\"  [ERROR] Failed to patch paths: {e}\")\n",
    "            results.append({\n",
    "                'name': name,\n",
    "                'type': nb_type,\n",
    "                'status': 'FAILED',\n",
    "                'duration': 0.0,\n",
    "                'error': f\"Path patching failed: {e}\"\n",
    "            })\n",
    "            continue\n",
    "\n",
    "        ep = ExecutePreprocessor(timeout=parsed_args.timeout, kernel_name='python3')\n",
    "        start_time = time.time()\n",
    "        status = 'PASSED'\n",
    "        error_msg = None\n",
    "        \n",
    "        try:\n",
    "            with open(sandbox_nb_path, 'r', encoding='utf-8') as f:\n",
    "                nb_obj = nbformat.read(f, as_version=4)\n",
    "            print(f\"  Executing cells in background dialog dismiss context...\")\n",
    "            with agent.dialog_dismiss_context(title='Studio RM'):\n",
    "                ep.preprocess(nb_obj, {'metadata': {'path': sandbox_dir}})\n",
    "        except CellExecutionError as e:\n",
    "            status = 'FAILED'\n",
    "            error_msg = f\"CellExecutionError:\\n{e}\"\n",
    "            print(f\"  [FAILED] Cell execution error in notebook.\")\n",
    "        except Exception as e:\n",
    "            status = 'FAILED'\n",
    "            error_msg = f\"Exception:\\n{e}\\n{traceback.format_exc()}\"\n",
    "            print(f\"  [FAILED] Unexpected exception during run: {e}\")\n",
    "        \n",
    "        duration = time.time() - start_time\n",
    "        print(f\"  Result: {status} ({duration:.2f}s)\")\n",
    "        \n",
    "        result_nb_file = f\"{name}_{status.lower()}.ipynb\"\n",
    "        result_nb_path = os.path.join(results_dir, result_nb_file)\n",
    "        try:\n",
    "            with open(result_nb_path, 'w', encoding='utf-8') as f:\n",
    "                nbformat.write(nb_obj, f)\n",
    "            print(f\"  Saved evaluated notebook to {os.path.relpath(result_nb_path, repo_root)}\")\n",
    "        except Exception as e:\n",
    "            print(f\"  [Warning] Failed to save evaluated notebook: {e}\")\n",
    "\n",
    "        results.append({\n",
    "            'name': name,\n",
    "            'type': nb_type,\n",
    "            'status': status,\n",
    "            'duration': duration,\n",
    "            'error': error_msg\n",
    "        })\n",
    "\n",
    "    clear_sandbox(sandbox_dir)\n",
    "\n",
    "    summary_path = os.path.join(results_dir, 'summary.md')\n",
    "    passed_count = sum(1 for r in results if r['status'] == 'PASSED')\n",
    "    failed_count = sum(1 for r in results if r['status'] == 'FAILED')\n",
    "    total_duration = sum(r['duration'] for r in results)\n",
    "\n",
    "    with open(summary_path, 'w', encoding='utf-8') as f:\n",
    "        f.write(f\"# dmstudio Notebook Test Summary Report\\n\\n\")\n",
    "        f.write(f\"- **Run ID:** `{run_id}`\\n\")\n",
    "        f.write(f\"- **Timestamp:** {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\\n\")\n",
    "        f.write(f\"- **Total Notebooks Run:** {len(results)}\\n\")\n",
    "        f.write(f\"- **Passed:** {passed_count}\\n\")\n",
    "        f.write(f\"- **Failed:** {failed_count}\\n\")\n",
    "        f.write(f\"- **Total Execution Time:** {total_duration:.2f}s\\n\\n\")\n",
    "        f.write(f\"## Detailed Results\\n\\n\")\n",
    "        f.write(f\"| Name | Type | Status | Duration (s) | Error Details |\\n\")\n",
    "        f.write(f\"| --- | --- | --- | --- | --- |\\n\")\n",
    "        for r in results:\n",
    "            err_summary = r['error'].replace('\\n', '<br>') if r['error'] else ''\n",
    "            f.write(f\"| {r['name']} | {r['type']} | **{r['status']}** | {r['duration']:.2f} | {err_summary} |\\n\")\n",
    "\n",
    "    print(\"\\n\" + \"=\" * 60)\n",
    "    print(\"TESTING FINISHED\")\n",
    "    print(f\"Total: {len(results)} | Passed: {passed_count} | Failed: {failed_count}\")\n",
    "    print(f\"Total Time: {total_duration:.2f}s\")\n",
    "    print(f\"Summary Report: {os.path.relpath(summary_path, repo_root)}\")\n",
    "    print(\"=\" * 60)\n"
]

# Find the code cell containing "def run_test_suite" and replace its source
patched = False
for cell in nb['cells']:
    if cell['cell_type'] == 'code' and any('def run_test_suite' in line for line in cell['source']):
        cell['source'] = helper_code_lines
        patched = True
        break
if not patched:
    print("Warning: could not find the run_test_suite cell to patch!")

with open(notebook_path, 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1)

print("Successfully restored and patched run_tests.ipynb helper cell!")
